package tudien;

import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.io.IOException;
import javax.swing.ImageIcon;
import java.util.ArrayList;
import java.util.Arrays;
import static java.util.Arrays.binarySearch;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.ListModel;
import javax.swing.UnsupportedLookAndFeelException;

public class DoHoa extends javax.swing.JFrame {

    DictionaryCommandline dic = new DictionaryCommandline();
    DefaultListModel listModel = new DefaultListModel();
    int n = dic.word.size();

    private String[] arr(String[] arr) {
        for (int i = 0; i < dic.word.size(); i++) {
            arr[i] = dic.word.get(i).getWordTarget();
        }
        return arr;
    }

    private void insertWord() {
        dic.insertFromFile();

    }

    public int GetMaxWidth() {
        return GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds().width;
    }

    public int GetMaxHeight() {
        return GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds().height;
    }
    // set the MAXIMUM size....

    private void inWt() {
        for (int i = 0; i < dic.word.size(); i++) {

            listModel.addElement(dic.word.get(i).getWordTarget());

        }

        listWord.setModel(listModel);
    }

    /**
     * Creates new form DoHoa
     */
    public DoHoa() {
        initComponents();
        insertWord();
        inWt();
        setSize(1400, 780);
    }

    @Override
    public void paint(Graphics draw) {

        getContentPane().setBackground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        textWord = new javax.swing.JTextField();
        btSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listWord = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btChange = new javax.swing.JButton();
        btRemove = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btClear = new javax.swing.JButton();
        btSpeak = new javax.swing.JButton();
        btEV = new javax.swing.JButton();
        btVE = new javax.swing.JButton();
        btLoad = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaExplain = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        textAdd = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaAdd = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btAdd = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        areaTrans = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        areaAdExplain = new javax.swing.JTextArea();
        cbTrans = new javax.swing.JComboBox<>();
        cbExplain = new javax.swing.JComboBox<>();
        btAdvanced = new javax.swing.JButton();
        btAdSpeak = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        textWord.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textWord.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 255)));
        textWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textWordActionPerformed(evt);
            }
        });
        textWord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textWordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textWordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textWordKeyTyped(evt);
            }
        });

        btSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lupa-de-buscador.png"))); // NOI18N
        btSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 255)));
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });

        listWord.setBackground(new java.awt.Color(0, 0, 0));
        listWord.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 255)));
        listWord.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        listWord.setForeground(new java.awt.Color(255, 255, 255));
        listWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listWordMouseClicked(evt);
            }
        });
        listWord.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listWordValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listWord);
        listWord.getAccessibleContext().setAccessibleDescription("");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ephoto360.com-5bc70f53f295e.jpg"))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("UVF Bleeding Cowboys", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Từ Điển");

        btChange.setBackground(new java.awt.Color(0, 0, 0));
        btChange.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btChange.setForeground(new java.awt.Color(51, 51, 255));
        btChange.setText("Change Word");
        btChange.setToolTipText("Change selected word");
        btChange.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 255)));
        btChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChangeActionPerformed(evt);
            }
        });

        btRemove.setBackground(new java.awt.Color(0, 0, 0));
        btRemove.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btRemove.setForeground(new java.awt.Color(0, 0, 255));
        btRemove.setText("Remove Word");
        btRemove.setToolTipText("Remove selected word");
        btRemove.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 255)));
        btRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Copyright @ 2018 by Team GCĐ ");

        btClear.setBackground(new java.awt.Color(0, 0, 0));
        btClear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btClear.setForeground(new java.awt.Color(0, 0, 255));
        btClear.setText("Clear");
        btClear.setToolTipText("Clear all word");
        btClear.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });

        btSpeak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-speaker-50.png"))); // NOI18N
        btSpeak.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 255)));
        btSpeak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSpeakActionPerformed(evt);
            }
        });

        btEV.setBackground(new java.awt.Color(0, 0, 0));
        btEV.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btEV.setForeground(new java.awt.Color(0, 0, 204));
        btEV.setText("E-V");
        btEV.setToolTipText("Translate English to Vietnamese");
        btEV.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        btEV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEVActionPerformed(evt);
            }
        });

        btVE.setBackground(new java.awt.Color(0, 0, 0));
        btVE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btVE.setForeground(new java.awt.Color(0, 0, 204));
        btVE.setText("V-E");
        btVE.setToolTipText("Translate Vietnamese to English");
        btVE.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 255)));
        btVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVEActionPerformed(evt);
            }
        });

        btLoad.setBackground(new java.awt.Color(0, 0, 0));
        btLoad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btLoad.setForeground(new java.awt.Color(0, 0, 255));
        btLoad.setText("Load Data");
        btLoad.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        btLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoadActionPerformed(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 204));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTabbedPane1.setOpaque(true);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        areaExplain.setBackground(new java.awt.Color(0, 0, 0));
        areaExplain.setColumns(20);
        areaExplain.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        areaExplain.setForeground(new java.awt.Color(255, 255, 255));
        areaExplain.setLineWrap(true);
        areaExplain.setRows(5);
        areaExplain.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 204)));
        jScrollPane2.setViewportView(areaExplain);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1172, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Explain", jPanel3);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        textAdd.setBackground(new java.awt.Color(0, 0, 0));
        textAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textAdd.setForeground(new java.awt.Color(255, 255, 255));
        textAdd.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 255)));

        areaAdd.setBackground(new java.awt.Color(0, 0, 0));
        areaAdd.setColumns(20);
        areaAdd.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        areaAdd.setForeground(new java.awt.Color(255, 255, 255));
        areaAdd.setRows(5);
        areaAdd.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 204)));
        jScrollPane3.setViewportView(areaAdd);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Input word");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText(" Input Word Explain");

        btAdd.setBackground(new java.awt.Color(0, 0, 0));
        btAdd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btAdd.setForeground(new java.awt.Color(0, 0, 204));
        btAdd.setText("Add Word");
        btAdd.setToolTipText("Add word in dictionary");
        btAdd.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 255)));
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 204));
        jButton1.setText("Clear");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(textAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        btAdd.getAccessibleContext().setAccessibleParent(jPanel1);

        jTabbedPane1.addTab("Add/Change Word", jPanel4);
        jPanel4.getAccessibleContext().setAccessibleParent(jPanel2);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 204)));

        areaTrans.setBackground(new java.awt.Color(0, 0, 0));
        areaTrans.setColumns(20);
        areaTrans.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        areaTrans.setForeground(new java.awt.Color(255, 255, 255));
        areaTrans.setLineWrap(true);
        areaTrans.setRows(5);
        areaTrans.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 204)));
        jScrollPane4.setViewportView(areaTrans);

        areaAdExplain.setBackground(new java.awt.Color(0, 0, 0));
        areaAdExplain.setColumns(20);
        areaAdExplain.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        areaAdExplain.setForeground(new java.awt.Color(255, 255, 255));
        areaAdExplain.setLineWrap(true);
        areaAdExplain.setRows(5);
        areaAdExplain.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 204)));
        jScrollPane5.setViewportView(areaAdExplain);

        cbTrans.setBackground(new java.awt.Color(0, 0, 0));
        cbTrans.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbTrans.setForeground(new java.awt.Color(0, 0, 204));
        cbTrans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "Vietnamese" }));
        cbTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTransActionPerformed(evt);
            }
        });

        cbExplain.setBackground(new java.awt.Color(0, 0, 0));
        cbExplain.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbExplain.setForeground(new java.awt.Color(0, 0, 204));
        cbExplain.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "Vietnamese" }));

        btAdvanced.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lupa-de-buscador.png"))); // NOI18N
        btAdvanced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdvancedActionPerformed(evt);
            }
        });

        btAdSpeak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-speaker-50.png"))); // NOI18N
        btAdSpeak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdSpeakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btAdvanced, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAdSpeak, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cbTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(cbExplain, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbExplain, cbTrans});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbExplain, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 135, Short.MAX_VALUE)
                        .addComponent(btAdvanced, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAdSpeak)
                        .addGap(244, 244, 244))
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btAdSpeak, btAdvanced});

        cbTrans.getAccessibleContext().setAccessibleParent(jLabel1);

        jTabbedPane1.addTab("Advanced Translate", jPanel5);
        jPanel5.getAccessibleContext().setAccessibleParent(jPanel2);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 255));
        jButton2.setText("Save");
        jButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 255)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btEV, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(btVE, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(textWord, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btSpeak, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)
                        .addComponent(btChange, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(btRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btClear, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(btEV, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(btVE, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel3)))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textWord, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btSpeak, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(btChange, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(btRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(btClear, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btChange.getAccessibleContext().setAccessibleParent(jPanel1);
        btRemove.getAccessibleContext().setAccessibleParent(jPanel1);
        jTabbedPane1.getAccessibleContext().setAccessibleName("");
        jTabbedPane1.getAccessibleContext().setAccessibleParent(jTabbedPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textWordActionPerformed
        if (!textWord.getText().equals("")) {
            String[] w = new String[dic.word.size()];
            int i = 0;
            while (i < dic.word.size()) {
                w[i] = dic.word.get(i).getWordTarget();
                i++;
            }
            int index = Arrays.binarySearch(w, textWord.getText());
            if (index < 0) {
                JOptionPane.showMessageDialog(null, "Word Cannot Found!");
            } else {
                areaExplain.setText(dic.word.get(index).getWordExplain());
            }
        }
    }//GEN-LAST:event_textWordActionPerformed

    private void listWordValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listWordValueChanged
        for (int i = 0; i < dic.word.size(); i++) {
            if (listWord.getSelectedValue().equals(dic.word.get(i).getWordTarget())) {
                areaExplain.setText(dic.word.get(i).getWordExplain());
            } else {
                continue;
            }
        }

    }//GEN-LAST:event_listWordValueChanged

    private void textWordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textWordKeyReleased
        try {
            DefaultListModel listModel1 = new DefaultListModel();
            for (int i = 0; i < dic.word.size(); i++) {
                if (dic.word.get(i).getWordTarget().startsWith(textWord.getText())) {

                    listModel1.addElement(dic.word.get(i).getWordTarget());
                }

            }
            listWord.setModel(listModel1);

        } catch (NullPointerException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_textWordKeyReleased

    private void textWordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textWordKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_textWordKeyPressed

    private void textWordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textWordKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textWordKeyTyped

    private void listWordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listWordMouseClicked
        String selection = listWord.getSelectedValue().toString();
        textWord.setText(selection);
    }//GEN-LAST:event_listWordMouseClicked

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        ArrayList<Word> nword = dic.word;
        String wt = "", we = "";
        wt = textAdd.getText();
        we = areaAdd.getText();
        String[] w1 = new String[dic.word.size()];
        int i = 0;
        while (i < dic.word.size()) {
            w1[i] = dic.word.get(i).getWordTarget();
            i++;
        }
        int index = Arrays.binarySearch(w1, wt);
        if (wt.equals("") || we.equals("")) {
            JOptionPane.showMessageDialog(null, "Word or Explain is emty!");
        } else {
            if (index > 0) {
                JOptionPane.showMessageDialog(null, "Từ này đã tồn tại!");
            } else {
                Word wors = new Word(wt, we);
                dic.word.add(wors);
                listModel.addElement(wt);

                listWord.setModel(listModel);
                JOptionPane.showMessageDialog(null, "Done!");

            }
        }
    }//GEN-LAST:event_btAddActionPerformed

    private void btRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveActionPerformed
        if (!textWord.getText().equals("")) {
            int option = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn không?", "Remove Word", JOptionPane.OK_CANCEL_OPTION);
            if (option == JOptionPane.OK_OPTION) {
                int index = listWord.getSelectedIndex();
                dic.removeWord(textWord.getText());
                listModel.remove(index);
                listWord.setModel(listModel);
                areaExplain.setText("");
                textWord.setText("");
                JOptionPane.showMessageDialog(null, "Done!");
            }

        }
    }//GEN-LAST:event_btRemoveActionPerformed

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        dic.word.clear();
        listModel.clear();
        listWord.setModel(listModel);
        areaExplain.setText("");
        textWord.setText("");
    }//GEN-LAST:event_btClearActionPerformed

    private void btSpeakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSpeakActionPerformed
        Voice1 s = new Voice1("njdh");
        s.say(textWord.getText());
    }//GEN-LAST:event_btSpeakActionPerformed

    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed
        if (!textWord.getText().equals("")) {
            String[] w = new String[dic.word.size()];
            int i = 0;
            while (i < dic.word.size()) {
                w[i] = dic.word.get(i).getWordTarget();
                i++;
            }
            int index = Arrays.binarySearch(w, textWord.getText());
            if (index < 0) {
                JOptionPane.showMessageDialog(null, "Word Cannot Found!");
            } else {
                areaExplain.setText(dic.word.get(index).getWordExplain());
            }
        }
    }//GEN-LAST:event_btSearchActionPerformed

    private void btEVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEVActionPerformed
        String we = "";
        Translate translate = new Translate();
        String s = textWord.getText();

        String regax = "(?<!\\\\)" + Pattern.quote(".");
        String[] arr = s.split(regax);
        ArrayList<String> str = new ArrayList<>();
        for (String w : arr) {
            str.add(w + ". ");
        }
        for (String w : str) {
            try {
                we += translate.callTranslate("en", "vi", w);

            } catch (Exception ex) {
                Logger.getLogger(DoHoa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        areaExplain.setText(we);


    }//GEN-LAST:event_btEVActionPerformed

    private void btVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVEActionPerformed
        String we = "";
        Translate translate = new Translate();
        String s = textWord.getText();
        String regax = "(?<!\\\\)" + Pattern.quote(".");
        String[] arr = s.split(regax);
        ArrayList<String> str = new ArrayList<>();
        for (String w : arr) {
            str.add(w + ". ");
        }
        for (String w : str) {
            try {
                we += translate.callTranslate("vi", "en", w);

            } catch (Exception ex) {
                Logger.getLogger(DoHoa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        areaExplain.setText(we);


    }//GEN-LAST:event_btVEActionPerformed

    private void btLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoadActionPerformed
        dic.insertFromFile();
        inWt();
    }//GEN-LAST:event_btLoadActionPerformed

    private void btChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChangeActionPerformed

        if (areaExplain.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập nghĩa muốn thay đổi!");
        } else {
            String we = "";
            int option = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn không?", "Change explain", JOptionPane.OK_CANCEL_OPTION);
            if (option == JOptionPane.OK_OPTION) {
                we = areaExplain.getText();
                dic.changeWord(textWord.getText(), we);
                JOptionPane.showMessageDialog(null, "Done!");
            }
        }

    }//GEN-LAST:event_btChangeActionPerformed

    private void cbTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTransActionPerformed


    private void btAdvancedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdvancedActionPerformed

        if (cbTrans.getSelectedIndex() != cbExplain.getSelectedIndex()) {
            if (cbTrans.getSelectedIndex() == 0) {
                String we = "";
                Translate translate = new Translate();
                String s = areaTrans.getText();

                String regax = "(?<!\\\\)" + Pattern.quote(".");
                String[] arr = s.split(regax);
                ArrayList<String> str = new ArrayList<>();
                for (String w : arr) {
                    str.add(w + ". ");
                }
                for (String w : str) {
                    try {
                        we += translate.callTranslate("en", "vi", w);

                    } catch (Exception ex) {
                        Logger.getLogger(DoHoa.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                areaAdExplain.setText(we + " ");
            } else {
                String we = "";
                Translate translate = new Translate();
                String s = areaTrans.getText();
                String regax = "(?<!\\\\)" + Pattern.quote(".");
                String[] arr = s.split(regax);
                ArrayList<String> str = new ArrayList<>();
                for (String w : arr) {
                    str.add(w + ". ");
                }
                for (String w : str) {
                    try {
                        we += translate.callTranslate("vi", "en", w);

                    } catch (Exception ex) {
                        Logger.getLogger(DoHoa.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                areaAdExplain.setText(we);
            }
        } else {
            areaAdExplain.setText(areaTrans.getText());
        }
    }//GEN-LAST:event_btAdvancedActionPerformed

    private void btAdSpeakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdSpeakActionPerformed
        Voice1 s = new Voice1("njdh");
        s.say(areaTrans.getText());

    }//GEN-LAST:event_btAdSpeakActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        textAdd.setText("");
        areaAdd.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            dic.printfList();
        } catch (IOException ex) {
            Logger.getLogger(DoHoa.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Done!");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                new DoHoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaAdExplain;
    private javax.swing.JTextArea areaAdd;
    private javax.swing.JTextArea areaExplain;
    private javax.swing.JTextArea areaTrans;
    private javax.swing.JButton btAdSpeak;
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btAdvanced;
    private javax.swing.JButton btChange;
    private javax.swing.JButton btClear;
    private javax.swing.JButton btEV;
    private javax.swing.JButton btLoad;
    private javax.swing.JButton btRemove;
    private javax.swing.JButton btSearch;
    private javax.swing.JButton btSpeak;
    private javax.swing.JButton btVE;
    private javax.swing.JComboBox<String> cbExplain;
    private javax.swing.JComboBox<String> cbTrans;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> listWord;
    private javax.swing.JTextField textAdd;
    private javax.swing.JTextField textWord;
    // End of variables declaration//GEN-END:variables
}
